name: Deploy docker image on using terraform

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \ 
          -var="vpc_cidr_block=10.0.0.0/16" \
          -var="web_subnet=10.0.100.0/24" \
          -var="region=eu-central-1" \
          -var="subnet_zone=eu-central-1a" \
          -var="public_key=.challenge.pub" \
          -var="main_vpc_name=challenge" \
          -var="app_port=3001" 


      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply \ 
          -var="vpc_cidr_block=10.0.0.0/16" \
          -var="web_subnet=10.0.100.0/24" \
          -var="region=eu-central-1" \
          -var="subnet_zone=eu-central-1a" \
          -var="public_key=.challenge.pub" \
          -var="main_vpc_name=challenge" \
          -var="app_port=3001" \
          -replace aws_instance.weather_app \
          -auto-approve
