name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

env:
  APP_NAME: weather-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Compile TypeScript code
      - name: Compile TypeScript
        run: npm run build

      # Step 5: Set up Docker Buildx (for multi-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Get the current version from the VERSION file
      - name: Get current version
        id: version
        run: |
          if [ ! -f VERSION ]; then
            echo "0" > VERSION
          fi
          CURRENT_VERSION=$(cat VERSION)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
          
      # Step 8: Get date
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y%m%d)-$(date +%s)" >> $GITHUB_ENV

      # Step 9: Build and push the Docker image with the new version tag
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:${{ env.DATE }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:${{ env.DATE }}

      # Step 10: Tag the image as latest and push it
      - name: Tag the latest image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:${{ env.DATE }} ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:latest
